# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestconnexion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testconnexion(self):
    self.driver.get("https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "p-personal-checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".vector-user-menu-login span:nth-child(2)").click()
    self.driver.find_element(By.ID, "wpPassword1").click()
    self.driver.find_element(By.ID, "wpPassword1").send_keys("W_D/ginTKxRr5CX")
    self.driver.find_element(By.ID, "wpName1").click()
    self.driver.find_element(By.ID, "wpName1").send_keys("juliette-ift")
    self.driver.find_element(By.ID, "userloginForm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mw-ui-checkbox > label").click()
    self.driver.find_element(By.ID, "wpLoginAttempt").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".accueil_2017_cadre:nth-child(1) img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".new > span").click()
    self.driver.find_element(By.ID, "p-personal-checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, "#pt-logout span:nth-child(2)").click()
  
