# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestrecherche():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testrecherche(self):
    self.driver.get("https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.NAME, "search").send_keys("Michou (vidéaste)")
    self.driver.find_element(By.CSS_SELECTOR, ".cdx-button").click()
    self.driver.find_element(By.NAME, "search").send_keys("inoxtag")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "search").send_keys("joyca")
    self.driver.find_element(By.CSS_SELECTOR, ".cdx-button").click()
  
