# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestconnexionfirefox():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testconnexionfirefox(self):
    self.driver.get("https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal")
    self.driver.set_window_size(1296, 1029)
    self.driver.find_element(By.ID, "p-personal-checkbox").click()
    self.driver.find_element(By.LINK_TEXT, "Se connecter").click()
    self.driver.find_element(By.ID, "wpName1").click()
    self.driver.find_element(By.ID, "wpName1").send_keys("bricetrp")
    self.driver.find_element(By.ID, "wpPassword1").send_keys("123456tra!")
    self.driver.find_element(By.CSS_SELECTOR, ".mw-ui-checkbox > label").click()
    self.driver.find_element(By.ID, "wpLoginAttempt").click()
    element = self.driver.find_element(By.NAME, "search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.NAME, "search").send_keys("inoxtag")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.NAME, "search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.close()
  
