# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestrecherchefirefox():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testrecherchefirefox(self):
    self.driver.get("https://fr.wikipedia.org/wiki/Wiki")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.NAME, "search").send_keys("François Hollande")
    self.driver.find_element(By.CSS_SELECTOR, ".cdx-button").click()
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.NAME, "search").send_keys("emmanuel macron")
    self.driver.find_element(By.CSS_SELECTOR, ".cdx-button").click()
    self.driver.find_element(By.NAME, "search").send_keys("jacques chirac")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
  
